@baseUrl = http://localhost:3000

### Try to login an adminuser
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}


### Read all Users with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/auths

### Delete member with ID == 2
DELETE {{baseUrl}}/auths/2

### Read member with ID == 2
GET {{baseUrl}}/auths/2

### Read member with username == admin

GET {{baseUrl}}/admin


### Get informations from username (5)
POST {{baseUrl}}/auths/username
Content-Type: application/json

{
    "username": "admin"
}

### Modifier Menu 
POST {{baseUrl}}/auths/addMenuLike
Content-Type: application/json

{
    "username": "admin",
    "menuId": 6
}



### Get id from username (5)
POST {{baseUrl}}/auths/readUserFromUsername
Content-Type: application/json

{
    "username": "HAZIKO22"
}


### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}


### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"maa",
    "email":"muahmma",
    "password":"manager",
    "phone":"0492488977",
    "adresse":"RUE DE S"
}

### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"dilhaa",
    "email":"muahmma",
    "password":"manager",
    "phone":"0492488977",
    "adresse":"RUE DE S"
}




### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manag",
    "password":"manager"
}