@baseUrl = http://localhost:3000

POST {{baseUrl}}/cart/addMenuToPanier
Content-Type: application/json

{
    "username": "admin",
    "idmenu": 4
}

### Get informations from username (5)
POST  {{baseUrl}}/cart/readcarteFromUsername
Content-Type: application/json

{
    "username": "manager"
}


### Delete the Menu with ID == 2
DELETE {{baseUrl}}/cart/deleteamenu

{
    "idmenu": 2,
    "username": "admin",
}


### Get informations from username (5)
DELETE  {{baseUrl}}/cart/deletepaniertotal
Content-Type: application/json

{
    "username": "haziq"
}

